name: matlab

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]

jobs:
  matlab:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v1

      - run: |
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV
          VERBOSE=1 pip install --verbose -e .

      - run: echo "m = py.importlib.import_module('cmake_example');\n m.add(1,2)" > test.m

      - uses: matlab-actions/setup-matlab@v0
        with:
          release: R2022a

      - uses: matlab-actions/run-command@v0
        with:
          command: test
